name: Deploy to Remote Machine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAgEArqeb4sTp+jTPWH1XCEdsRA4Dt9+PWA7RRwp9Dv0nAbCWzmM9Teak
fvrKE7j0pXHRGgezF3Xmjkb+kCf+uXbVQDQiUfOXrn7qXK/lMpMw9g0Qt0zYnd1WW9y2lX
Ez646B+Q/RGyLazVT1iCyWpffZoR49cj5URN4ANpOhlKtsnNczdytB9YU67KZnMNIgRC95
iLx102B+1GYh/bJmT5GtOKhwOyDjG/NSjGa55oxNIweFPwSgOlPIL/sYTlzY+1WHrz92mM
JbqZubWkeNGFG2DdWoRpbbRNe4xgftda6c+dnlOd3EozG5nbsaXknqSHM52kZnmHAThSNw
HYSjOahm8jH0vLj7f6DwACk0uZ26kwjkvaIBPI1QYY+FhPfLuTFIpK3lwJkLwPo6wsXvR7
6QmjFQG6nm3mwjR712It3CvuMjmhyjDcnSkIdYiGzzXItln4HV+5lWDLMeMFlQ9vqXo3NQ
puq0sgy/JPaCcW7Pp3OwXDSlAcl1fgvtNubvoA3nU+IuoF0zfBN6tFv16GZZHGkH6OGyCT
4bI1RDlnqRd23/Pg/CxKVSejObnV07rFLCILyOUGnL3nSfYlG16fSGqtpNso/OAPzjLxP3
qOUjazfXZ/8koc3Pu12sEhGRtWNfZThzZ3Sz0sKWsExCg9FED8AYWTFyNO12hyn70YIXR7
8AAAdQQAboTEAG6EwAAAAHc3NoLXJzYQAAAgEArqeb4sTp+jTPWH1XCEdsRA4Dt9+PWA7R
Rwp9Dv0nAbCWzmM9TeakfvrKE7j0pXHRGgezF3Xmjkb+kCf+uXbVQDQiUfOXrn7qXK/lMp
Mw9g0Qt0zYnd1WW9y2lXEz646B+Q/RGyLazVT1iCyWpffZoR49cj5URN4ANpOhlKtsnNcz
dytB9YU67KZnMNIgRC95iLx102B+1GYh/bJmT5GtOKhwOyDjG/NSjGa55oxNIweFPwSgOl
PIL/sYTlzY+1WHrz92mMJbqZubWkeNGFG2DdWoRpbbRNe4xgftda6c+dnlOd3EozG5nbsa
XknqSHM52kZnmHAThSNwHYSjOahm8jH0vLj7f6DwACk0uZ26kwjkvaIBPI1QYY+FhPfLuT
FIpK3lwJkLwPo6wsXvR76QmjFQG6nm3mwjR712It3CvuMjmhyjDcnSkIdYiGzzXItln4HV
+5lWDLMeMFlQ9vqXo3NQpuq0sgy/JPaCcW7Pp3OwXDSlAcl1fgvtNubvoA3nU+IuoF0zfB
N6tFv16GZZHGkH6OGyCT4bI1RDlnqRd23/Pg/CxKVSejObnV07rFLCILyOUGnL3nSfYlG1
6fSGqtpNso/OAPzjLxP3qOUjazfXZ/8koc3Pu12sEhGRtWNfZThzZ3Sz0sKWsExCg9FED8
AYWTFyNO12hyn70YIXR78AAAADAQABAAACACopojM7UDSrvQZis7j27Qb8zx77ZDJg2Vqq
CIiuylTZGX7XbDw7GqjgyBm8w6qQ8Ga1RyG5v5/HObr5PL/vFQn7y/E2uf5Q+yjG+bCc4e
v0OX3WmlB511gzzwwCmQMbkvraO6OuZV2+TcvC39dPHwWLNFA5BcTeRvTl7NLkE0NFnFH/
alvn/tKUVULu5wUu5MsCm/scR2HlCf2hrJs20rdjyjwr80eTFPF59xTV9+Ul8p/E8R1Djo
cuua5pMaRzAF9pFatI+DHYs8c2kLQ3PZjXZFkuH97dqOh9j3CiZ5jVZkXy6H5xCZsvSO1M
MLeuwV+VMXsWS1APvwgRNgo8QiV9bA9k2LpI6w33JZtaomlv0syDKjEbvE3CFXrUKFp+j9
FuGQlcLAY0u5teEDa4f8czXM3eBo7BRM2RVKMI9B2tarS4SevTcQOcJMnCPDLi9MCv3VfJ
1Cz9LUvYKkOgVtEO6SlVvm4+3Z4M/22VB0O7mgsCUtYEJ15T6IGLtsbvD12zKeUeHdwj9t
Dtn7GKqslVaiUkjvNpoBCTFNAXiVNkwJkP0fPK+GFi2C5L55DRS73YyXfRjJhpT/qF9XTs
DAuQL7jFbtCC2EK/NYWdWsgt9L5yNsf0gEwS3hjFnIE5yLCFJs2dB+UWZKluOZJOheHGWV
qCsXkIkW+ZJduojXEJAAABAFROxNjFYiYYRsMkzTxq+LIgN+m6wU2hvQZ+GPmbuo6CgjQ0
l5NEN287caeG0eOBiKSypBaqLsyEpcyhWyhhgHT41GlgBOt5Zu+ZwYCU+KGh+X5grMwIm8
/eWvzAbWz2k0FItz7Ek5XN49EljDlMuf45gKt3Gp9pXrYK+AB3a87iwGXSGLVEEOgj0n1D
0QcIch7CvkVvaQQArGku+0bdBf3sDtzbfJJ0maaBDSWCkV7D2WfuNaN9jP6EFOEx6XZddj
V4zYSIDFvUGjcDQ+VY3TT6kB8UKlN/ZbrgRoLcjUKIpF6l9tO59hHHk40fBH4PJUNDwFrr
kKOiKHqPFYFUczIAAAEBAOCrvpWrNBUOTcf59MoIDHMnW+6DkdGSw+oh8WufYrWrA0FZOL
HWCOqpNKNRuHfGxNGW68vr1sAqb/MilE3kH+t7oB5yOHoC9KXK4kVrzbFAJCcHuuM25WKq
5QrOFswkgyPF7b7AJJzgg+7WBypysyh3F7XJPWp+RP309uNzsuoLlvN5v222ZFBDHT+8sF
wBYBX1+LNHPclD9wm9rAN30WtOqEcUlHF6B0st1BEntIymqQKjs6m6LTt3rOXdnIi/QHgm
oe/KP8P3fN13H50ML+UO/hE8tKVVbDcBVK0tDf/sdYh0JRfVaX4nZHhkuAaXFtcB2qkq+9
EiJGeola8KPAMAAAEBAMcCZdwdfAvy7nTpoQv6j/+bwIXEoep2/msiKGs5xhGPbHsnIha6
L9pWBgq9MnNb669uWJTRvVKgqLOObwgkBwC2GbEPxgfv/H7TkZ7M8LZkZkLGwBoSjS8tdN
5HI4RhRakyiGMvVpxix+MIKxbEd9kFiwnz/AzO9OlrYwq+gDIkLzG8I66aZHrKpSoYxfVV
nayj9oNNIqmuFg5W8IcIICTEZMfvlQL1tu3nsR8Qir+TyZf60N57lOAnNbBz6tJmSYQYhN
WtenwCywboyx/LJ/V7+/rdAGBpV5hJj/oMCHQqU7zCOmuqjJHVKJp0waUJGizJhf20RX0N
XVQ42HdeHpUAAAAWeW91cl9lbWFpbEBleG" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 188.65.93.0 >> ~/.ssh/known_hosts

      - name: SSH into Remote Machine
        run: |
          ssh -v -i ~/.ssh/id_rsa sads@188.65.93.0

      - name: go to project directory
        run: |
          cd Documents/go/pokeGo

      - name: delete old binary
        run: |
          rm app

      - name: get new code
        run: |
          git pull

      - name: build new binary
        run: |
          go build -o app *.go

      - name: stop old server
        run: |
          pm2 delete pokeGo

      - name: start new server
        run: |
          go build -o app *.go
