name: Deploy to Remote Machine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "-----BEGIN OPENSSH PRIVATE KEY-----b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcnNhAAAAAwEAAQAAAgEArqeb4sTp+jTPWH1XCEdsRA4Dt9+PWA7RRwp9Dv0nAbCWzmM9TeakfvrKE7j0pXHRGgezF3Xmjkb+kCf+uXbVQDQiUfOXrn7qXK/lMpMw9g0Qt0zYnd1WW9y2lXEz646B+Q/RGyLazVT1iCyWpffZoR49cj5URN4ANpOhlKtsnNczdytB9YU67KZnMNIgRC95iLx102B+1GYh/bJmT5GtOKhwOyDjG/NSjGa55oxNIweFPwSgOlPIL/sYTlzY+1WHrz92mMJbqZubWkeNGFG2DdWoRpbbRNe4xgftda6c+dnlOd3EozG5nbsaXknqSHM52kZnmHAThSNwHYSjOahm8jH0vLj7f6DwACk0uZ26kwjkvaIBPI1QYY+FhPfLuTFIpK3lwJkLwPo6wsXvR76QmjFQG6nm3mwjR712It3CvuMjmhyjDcnSkIdYiGzzXItln4HV+5lWDLMeMFlQ9vqXo3NQpuq0sgy/JPaCcW7Pp3OwXDSlAcl1fgvtNubvoA3nU+IuoF0zfBN6tFv16GZZHGkH6OGyCT4bI1RDlnqRd23/Pg/CxKVSejObnV07rFLCILyOUGnL3nSfYlG16fSGqtpNso/OAPzjLxP3qOUjazfXZ/8koc3Pu12sEhGRtWNfZThzZ3Sz0sKWsExCg9FED8AYWTFyNO12hyn70YIXR78AAAdQQAboTEAG6EwAAAAHc3NoLXJzYQAAAgEArqeb4sTp+jTPWH1XCEdsRA4Dt9+PWA7RRwp9Dv0nAbCWzmM9TeakfvrKE7j0pXHRGgezF3Xmjkb+kCf+uXbVQDQiUfOXrn7qXK/lMpMw9g0Qt0zYnd1WW9y2lXEz646B+Q/RGyLazVT1iCyWpffZoR49cj5URN4ANpOhlKtsnNczdytB9YU67KZnMNIgRC95iLx102B+1GYh/bJmT5GtOKhwOyDjG/NSjGa55oxNIweFPwSgOlPIL/sYTlzY+1WHrz92mMJbqZubWkeNGFG2DdWoRpbbRNe4xgftda6c+dnlOd3EozG5nbsaXknqSHM52kZnmHAThSNwHYSjOahm8jH0vLj7f6DwACk0uZ26kwjkvaIBPI1QYY+FhPfLuTFIpK3lwJkLwPo6wsXvR76QmjFQG6nm3mwjR712It3CvuMjmhyjDcnSkIdYiGzzXItln4HV+5lWDLMeMFlQ9vqXo3NQpuq0sgy/JPaCcW7Pp3OwXDSlAcl1fgvtNubvoA3nU+IuoF0zfBN6tFv16GZZHGkH6OGyCT4bI1RDlnqRd23/Pg/CxKVSejObnV07rFLCILyOUGnL3nSfYlG16fSGqtpNso/OAPzjLxP3qOUjazfXZ/8koc3Pu12sEhGRtWNfZThzZ3Sz0sKWsExCg9FED8AYWTFyNO12hyn70YIXR78AAAADAQABAAACACopojM7UDSrvQZis7j27Qb8zx77ZDJg2VqqCIiuylTZGX7XbDw7GqjgyBm8w6qQ8Ga1RyG5v5/HObr5PL/vFQn7y/E2uf5Q+yjG+bCc4ev0OX3WmlB511gzzwwCmQMbkvraO6OuZV2+TcvC39dPHwWLNFA5BcTeRvTl7NLkE0NFnFH/alvn/tKUVULu5wUu5MsCm/scR2HlCf2hrJs20rdjyjwr80eTFPF59xTV9+Ul8p/E8R1Djocuua5pMaRzAF9pFatI+DHYs8c2kLQ3PZjXZFkuH97dqOh9j3CiZ5jVZkXy6H5xCZsvSO1MMLeuwV+VMXsWS1APvwgRNgo8QiV9bA9k2LpI6w33JZtaomlv0syDKjEbvE3CFXrUKFp+j9FuGQlcLAY0u5teEDa4f8czXM3eBo7BRM2RVKMI9B2tarS4SevTcQOcJMnCPDLi9MCv3VfJ1Cz9LUvYKkOgVtEO6SlVvm4+3Z4M/22VB0O7mgsCUtYEJ15T6IGLtsbvD12zKeUeHdwj9tDtn7GKqslVaiUkjvNpoBCTFNAXiVNkwJkP0fPK+GFi2C5L55DRS73YyXfRjJhpT/qF9XTsDAuQL7jFbtCC2EK/NYWdWsgt9L5yNsf0gEwS3hjFnIE5yLCFJs2dB+UWZKluOZJOheHGWVqCsXkIkW+ZJduojXEJAAABAFROxNjFYiYYRsMkzTxq+LIgN+m6wU2hvQZ+GPmbuo6CgjQ0l5NEN287caeG0eOBiKSypBaqLsyEpcyhWyhhgHT41GlgBOt5Zu+ZwYCU+KGh+X5grMwIm8/eWvzAbWz2k0FItz7Ek5XN49EljDlMuf45gKt3Gp9pXrYK+AB3a87iwGXSGLVEEOgj0n1D0QcIch7CvkVvaQQArGku+0bdBf3sDtzbfJJ0maaBDSWCkV7D2WfuNaN9jP6EFOEx6XZddjV4zYSIDFvUGjcDQ+VY3TT6kB8UKlN/ZbrgRoLcjUKIpF6l9tO59hHHk40fBH4PJUNDwFrrkKOiKHqPFYFUczIAAAEBAOCrvpWrNBUOTcf59MoIDHMnW+6DkdGSw+oh8WufYrWrA0FZOLHWCOqpNKNRuHfGxNGW68vr1sAqb/MilE3kH+t7oB5yOHoC9KXK4kVrzbFAJCcHuuM25WKq5QrOFswkgyPF7b7AJJzgg+7WBypysyh3F7XJPWp+RP309uNzsuoLlvN5v222ZFBDHT+8sFwBYBX1+LNHPclD9wm9rAN30WtOqEcUlHF6B0st1BEntIymqQKjs6m6LTt3rOXdnIi/QHgmoe/KP8P3fN13H50ML+UO/hE8tKVVbDcBVK0tDf/sdYh0JRfVaX4nZHhkuAaXFtcB2qkq+9EiJGeola8KPAMAAAEBAMcCZdwdfAvy7nTpoQv6j/+bwIXEoep2/msiKGs5xhGPbHsnIha6L9pWBgq9MnNb669uWJTRvVKgqLOObwgkBwC2GbEPxgfv/H7TkZ7M8LZkZkLGwBoSjS8tdN5HI4RhRakyiGMvVpxix+MIKxbEd9kFiwnz/AzO9OlrYwq+gDIkLzG8I66aZHrKpSoYxfVVnayj9oNNIqmuFg5W8IcIICTEZMfvlQL1tu3nsR8Qir+TyZf60N57lOAnNbBz6tJmSYQYhNWtenwCywboyx/LJ/V7+/rdAGBpV5hJj/oMCHQqU7zCOmuqjJHVKJp0waUJGizJhf20RX0NXVQ42HdeHpUAAAAWeW91cl9lbWFpbEBleG" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 188.65.93.0 >> ~/.ssh/known_hosts

      - name: SSH into Remote Machine
        run: |
          ssh -v -i ~/.ssh/id_rsa sads@188.65.93.0

      - name: go to project directory
        run: |
          cd Documents/go/pokeGo

      - name: delete old binary
        run: |
          rm app

      - name: get new code
        run: |
          git pull

      - name: build new binary
        run: |
          go build -o app *.go

      - name: stop old server
        run: |
          pm2 delete pokeGo

      - name: start new server
        run: |
          go build -o app *.go
